export const GET_TASK_REQUEST  = "GET_TASK_REQUEST";
export const GET_TASK_SUCCESSS = "GET_TASK_SUCCESSS";
export const GET_TASK_FAIL = "GET_TASK_FAIL";

export const GET_STASK_REQUEST  = "GET_STASK_REQUEST";
export const GET_STASK_SUCCESSS = "GET_STASK_SUCCESSS";
export const GET_STASK_FAIL = "GET_STASK_FAIL";